### ISSUE TITLE
Rate card changes

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#2188] opened 2019-08-26 20:14 UTC
- [x] Send notice
- [x] Payout based on the download region
- [ ] New calculations start occurring October (new payout changes don't show up until November)

**Comment by corymcdonald** [comment] 2019-09-13 16:57
Related Ledger PR: https://github.com/brave-intl/bat-ledger/pull/713

**Comment by corymcdonald** [comment] 2019-10-07 21:09
Closing as duplicate of #2288

**Closed by corymcdonald** 2019-10-07 21:09 UTC
Labels: P2
