### ISSUE TITLE
Suspended Publishers List on Admin

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1645] opened 2019-02-25 21:10 UTC
- [ ] I'll follow up on Slack with BE and @atsyed87 .

**Comment by corymcdonald** [comment] 2019-02-25 21:54
Is this a duplicate of this
https://github.com/brave-intl/publishers/issues/1146

**Comment by corymcdonald** [comment] 2019-02-26 18:21
This is going to come in 2 parts
1. allow for administrator to upload gordon report to suspend pubs via csv
2. ensure that notes field is updated when admin updates the status field so we can know exactly why we are banning vs unbanning

We also wanna give away TOO many details, so let's have a warning to the administrator saying "Please do not give away specifics"

**Closed** 2019-03-20 17:05 UTC
Labels: 2, P2
