### ISSUE TITLE
Add locale support to stylesheets

### ISSUE THREAD

**Issue by lgebhardt** [brave-intl/publishers#256] opened 2017-11-11 13:30 UTC
We're introducing limited content into the stylesheets for the overlay text on the Publication Type chooser page (email_verified). These strings should be able to be translated, so the stylesheets need to support internationalization. In addition different languages may need different text (fonts, spacing, etc) styles and language specific images.

Based on very limited research I see we could handle this in several ways. Two are linked below, though others probably exist:

https://stackoverflow.com/questions/11577083/access-the-locale-in-ruby-in-css-files
https://stackoverflow.com/questions/9310044/rails-i18n-of-css-file

Let's examine the current and future needs before settling on a strategy.

**Comment by mrose17** [comment] 2017-12-04 20:21
partial duplicate of https://github.com/brave-intl/publishers/issues/58

**Closed by mrose17** 2017-12-04 20:21 UTC
Labels: ui/ux
