### ISSUE TITLE
Silence or resolve `X is missing uphold_access_parameter`

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#2033] opened 2019-07-08 21:39 UTC

**Comment by corymcdonald** [comment] 2019-07-10 15:23
Pretty sure this is the root cause 
https://github.com/brave-intl/publishers/issues/1952

**Comment by corymcdonald** [comment] 2019-07-16 14:37
This wasn't addressed by the PR but will be fixed when we address #2048

**Closed** 2019-08-08 17:17 UTC
