### ISSUE TITLE
Website reverification may fail

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#697] opened 2018-03-01 22:06 UTC
As reported by Kamil for a Github site verification; it worked the first time then didn't work the second time.

**Comment by nvonpentz** [comment] 2018-03-02 15:19
Marshall confirmed that eyeshade returns 
```
{"status":"success","verificationId":"79c38769-f685-41e9-81f4-430e76031f43"}
```
For (SiteChannelVerifier)
```
get https://eyeshade.mercury.basicattentiontoken.org/v1/owners/publishers%23uuid:431b7f8c-a138-4bf8-bbb3-9d083f0ed453/verify/kjozwiak.github.io
```

So this is probably a problem with publishers.

**Comment by ayumi** [comment] 2018-03-02 19:09
I wonder if it's a problem with deleting records.
For our notes: Upon channel delete we make a request like this to Eyeshade:
`DELETE /v1/owners/#{URI.escape(@publisher.owner_identifier)}/#{URI.escape(channel_identifier)}`

e.g. for a site channel:

```
DELETE /v1/owners/publishers%23uuid:12345678-abcd-1234-abcd-1234abcd5678/example.com
```

e.g. for a YouTube channel:

```
DELETE /v1/owners/publishers%23uuid:12345678-abcd-1234-abcd-1234abcd5678/youtube%23channel:UCDISUw-d12ZxVBweK-aBClh
```

**Comment by lgebhardt** [comment] 2018-03-12 14:34
If the issue is related to trying to add a channel that was previously deleted I am unable to reproduce an error. It looks like channel deletes are flowing to eyeshade and eyeshade is removing the channel connections to an owner. This allows the same or a new user to add the channel again. Checked with both youtube and site channels.

**Comment by nvonpentz** [comment] 2018-03-13 19:04
@lgebhardt I think there is not problem with the current code; it should function correctly.

There was a bug in eyeshade that was addressed by https://github.com/brave-intl/bat-ledger/pull/150.  However, the tokens of verified channels that were removed before this was merged still persist in the eyeshade database (as verified).  Thus these channels are unable to reverify since Eyeshade thinks they already are verified.

I think we go with the process @mrose17 proposed, in which find the differences between the verified channels on publishers and eyeshade and use the publishers db as the source of truth to repair.

**Comment by mrose17** [comment] 2018-03-14 02:54
this is addressed by https://github.com/brave-intl/bat-ledger/pull/159, which is under review.

**Comment by yachtcaptain23** [comment] 2018-06-01 17:34
I believe this no longer applies since we handle verifications Publisher side.

**Closed by yachtcaptain23** 2018-06-01 17:34 UTC
Labels: Bug
