### ISSUE TITLE
Contribution balance 'Unavailable' doesn't seem to change

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#541] opened 2018-01-26 01:07 UTC
I was observing it to see when it becomes either '0' or disappears.

1. after adding at least one channel
2. after connecting the uphold account

none of above seems to affect. -- oh, is it because we're not talking to the backend yet???

![screen shot 2018-01-25 at 5 03 36 pm](https://user-images.githubusercontent.com/4369856/35420401-25eb91f2-01f2-11e8-9285-48efea8724b4.png)

**Comment by ayumi** [comment] 2018-01-26 01:10
yes, temporary error as Eyeshade hasn't been upgraded for Multi-chan yet

**Comment by jenn-rhim** [comment] 2018-01-26 01:17
gotcha! 👍  let me know when it's hooked up.

**Comment by ayumi** [comment] 2018-01-29 22:07
i tried this out in staging, creating a new owner account, and i think it's fixed now.

it's possible that owners previously created in staging could continue to show Unavailable due to data inconsistency.

**Comment by ayumi** [comment] 2018-02-09 22:01
i'm getting this issue on prod.

it was working at least a couple of days ago

manually querying my publisher.wallet.contribution_balance was successful

**Comment by nvonpentz** [comment] 2018-02-27 21:25
Can we close this? I believe this has been patched by some PR in eyeshade -- the publishers who had this issue have confirmed they no longer experience this.  @jenn-rhim @ayumi

**Closed** 2018-02-27 21:34 UTC
Labels: Bug
