### ISSUE TITLE
[WIP] Email - Contact email changed for YouTube Channel or Domain

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#423] opened 2017-12-21 17:17 UTC
Conditions :
A user has changed the contact email for a YouTube channel or domain they have verified.

Frequency :
Once

Subject :
Brave Payments noticed an email change for <_user verified channel_> || <_user verified domain_>

Body :

Salutation :
Hi <_username_>!

Paragraph :
We saw a change to your email address with Brave Payments:

Previous email: <_previous email_>
New email:<_new email_>

If you made this change, check your new email account for a link to confirm it.

If you did not make this change yourself, please contact support ASAP:<_publisher support email_>

**Comment by nvonpentz** [comment] 2018-01-09 15:09
I believe that this is already implemented.  This is the email to the old address:
![image](https://user-images.githubusercontent.com/12549658/34727216-445729ba-f524-11e7-9f49-74aa4a1f1665.png)

We also send another email to the new address:
![image](https://user-images.githubusercontent.com/12549658/34727403-c4a1c314-f524-11e7-86c7-dbc50f4940d4.png)

We might want to change the link to a button since it is pretty long.

@alexwykoff what else needs to be done for this?  Also, is this a duplicate of #430?

**Closed** 2018-03-14 16:37 UTC
Labels: Email
