### ISSUE TITLE
email not responsive

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#534] opened 2018-01-26 00:11 UTC
we do seem to detect the user agent: email on my mobile looks great.  but the email on my desktop browser is not responding to my viewport change.  hence needing to scroll.  horizontally! : o

**Comment by nvonpentz** [comment] 2018-03-19 13:27
@jenn-rhim Are you still experiencing this?  I cannot reproduce.

**Comment by nvonpentz** [comment] 2018-03-19 16:23
Closing with 'ok' from jenn

**Closed by nvonpentz** 2018-03-19 16:23 UTC
Labels: 3 P3, Email
