### ISSUE TITLE
Statement UI Fix

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#265] opened 2017-11-14 08:58 UTC
The following UI for the statement, enumerating all generated statement history is unscalable, and probably doesn't make sense for the users. 
https://github.com/brave-intl/publishers/pull/218

This issue is attempting to fix that.

**Comment by mrose17** [comment] 2017-11-14 17:06
@jenn-rhim - we need a description... thanks!

**Comment by TheLucasMoore** [comment] 2017-12-05 14:58
Hey Jenn is this addressed by https://github.com/brave-intl/publishers/pull/347?

**Comment by jenn-rhim** [comment] 2017-12-06 02:45
Yes, #347 serves as an interim solution. A preferred UX will be speced here.

**Comment by nvonpentz** [comment] 2018-04-13 14:26
Duplicate of #542

**Closed by nvonpentz** 2018-04-13 14:26 UTC
Labels: 3 P3
