### ISSUE TITLE
Renaming Twitch Channel Loses Tokens?

### ISSUE THREAD

**Issue by jonathansampson** [brave-intl/publishers#2014] opened 2019-06-30 16:02 UTC
From [a user on Twitter](https://twitter.com/TheCynicalKitty/status/1145350563762192384):

> I changed my twitch name from CruxedKat to TheCynicalKitty and there was no sync button so i though ohh ill be fine removing CruxedKat and I added TheCynicalKitty and iv lost my referrals and downloads since there tied to a username not ID based. Iv lost bat and stats from it.
> 
> My change to this i would make is have all account have an ID and then anything added is tied to that ID so if anythings removed later on what ever is earned goes to the ID and isn't bound to a Username, or update API's like twitch's to pull the user ID instead of username.
> 
> That way usernames can be changed without the worry of losing whats earned, and then on the brave publisher page add a sync button to check if anythings changed on twitch's end
> 
> Here's evidence i am who i am: https://twitch-tools.rootonline.de/username_changelogs_search.php?q=TheCynicalKitty

**Comment by jonathansampson** [comment] 2019-06-30 16:19
The issue here may be with the removal of a channel; doing so appears to reduce the projected payout for your account. In the above comment, the user believed it was necessary to remove their channel following a username change on the Twitch platform.

**Comment by tsmartt** [comment] 2021-05-18 19:27
Duplicate of #3172

**Closed by tsmartt** 2021-05-18 19:27 UTC
Labels: Bug 🐛, P2
