### ISSUE TITLE
need to fix the message for the 'channel taken' case

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#577] opened 2018-01-31 10:27 UTC
general guideline for the error message is to provide information as specific as possible if we have it. i feel the message on this screen didn't quite close it.

1. title: 'Channel taken': we know why we are 'unable to add' 
2. blurb below the title: 'The following YouTube channel has been already added **to a different account**' --> add this last part to clarify and complete the answer 
3. i'd just use 'added' only instead of 'added and verified' as adding was the user's triggering action.  in a certain context, if it's more appropriate that we spell out 'verified' and use along with added, i'd use the sequence, 'verified and added', not 'added and verified'.  
4. can we close the gap if we don't get the channel profile photo? it looks awkward that 'Brave Design' hanging in the middle of the line: i.e. left justify the channel name to the channel data block
5. use 'Added by' instead of 'Registered by'

![image](https://user-images.githubusercontent.com/4369856/35616914-87bfa2dc-062b-11e8-876a-0c1d64eb60c2.png)

**Comment by dgeb** [comment] 2018-01-31 16:47
@jenn-rhim Ok, all these changes are straightforward enough except for the missing channel photo, which I've been unable to reproduce.

I'm unclear if a channel profile photo url has been returned from YouTube and the URL is not resolving or whether the url returned is an empty string. Currently there is logic in place to show the default icon (see below) if no profile photo url is returned.

![screen shot 2018-01-31 at 11 42 25 am](https://user-images.githubusercontent.com/29122/35635398-355d849a-067c-11e8-92ff-a02c00d1fb21.png)

Do you not want the default icon above to ever appear for YouTube channels? Should we have a different default icon for YouTube?

**Comment by jenn-rhim** [comment] 2018-01-31 19:28
@dgeb  it looks like the owner for the channel above in the screenshot had uploaded a white/blank image (to trick me :) ), so disregard 4.

**Closed** 2018-01-31 22:14 UTC
