### ISSUE TITLE
Publisher settlement generation within Publishers

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#816] opened 2018-05-01 23:14 UTC
TBD cc @evq

**Comment by evq** [comment] 2018-05-15 19:40
When this is implemented we will want to change the logic for determining payout eligibility slightly, namely that channels must be verified one week prior to payout

**Comment by yachtcaptain23** [comment] 2018-07-06 17:17
Duplicate of https://github.com/brave-intl/publishers/issues/1006

**Closed by yachtcaptain23** 2018-07-06 17:17 UTC
Labels: epic / PSoT
