### ISSUE TITLE
Update appearance of the flash, related to the case where a channel has already been registered

### ISSUE THREAD

**Issue by lgebhardt** [brave-intl/publishers#267] opened 2017-11-14 12:51 UTC
From a slack conversation with @jenn-rhim:

jenn [11:08 PM] 
this is how i’d like to treat the case where the channel has been already claimed.  it’s level 1 warning as opposed to level 2 warning (alert bar).

jenn [11:08 PM] 
uploaded this image: 
![channel taken warning](https://user-images.githubusercontent.com/29154/32780747-650a078a-c910-11e7-857a-bb52edc90277.png)

jenn [11:09 PM] 
if this is not quick, we can make do with the current scheme until we can fix it, but i’d still use a little more catchy alert bar style, which we will use for other cases as well. here

jenn [11:09 PM] 
uploaded this image: 

![channel taken warning-alt](https://user-images.githubusercontent.com/29154/32780780-762092be-c910-11e7-9aa6-2dfd19345d79.png)

**Comment by mrose17** [comment] 2017-11-14 17:04
Duplicate of https://github.com/brave-intl/publishers/issues/264

**Closed by mrose17** 2017-11-14 17:04 UTC
Labels: phase-3
