### ISSUE TITLE
SMTP To address blank for some verification emails 

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#404] opened 2017-12-14 20:39 UTC
### Description
There is some case in which a verification email is scheduled, but fails to send because the `To:` field is blank.  The failing method is `PublisherMailer#verify_email`.

We should check to make sure there are working validations in all places that trigger this method. There should be no instance in which we allow an email to be scheduled if there is no email address associated with the publisher.

### Additional information
We first see this error on December 7th, which suggests recent modifications to the code might have enabled this.

~The full error report is in [sentry](https://sentry.io/brave-software/publishers-production-t2/issues/414805093/)~

This now corresponds to either of this sentry report:
https://sentry.io/brave-software/publishers-production-t2/issues/577126805

**Comment by ayumi** [comment] 2017-12-20 08:41
Good catch. This is happening pretty frequently and it affects a core email, so I think we should get to the bottom of this with a Sentry event closer to the source.

Could you add a check for blank To: headers around PublisherMailer #verify_email -- either within that mailer method or in the places which call that mailer method? If that check fails then we should send a message to Sentry.

**Comment by yachtcaptain23** [comment] 2018-05-25 17:31
@nvonpentz Would you see if this is still happening.

**Comment by nvonpentz** [comment] 2018-06-11 14:54
@yachtcaptain23 It looks like it still is.  I updated the original comment with the new sentry report.

**Comment by yachtcaptain23** [comment] 2019-03-27 05:23
Updated sentry report. Downgrading since it is very low severity https://sentry.io/organizations/brave-software/issues/890334091/?project=225116&query=publishermailer&statsPeriod=90d&utc=false

**Comment by yachtcaptain23** [comment] 2020-05-08 19:20
Duplicate of https://github.com/brave-intl/publishers/issues/2680. Will handle the fix there

**Closed by yachtcaptain23** 2020-05-08 19:20 UTC
Labels: P4
