### ISSUE TITLE
Notify users who have deauthorized BAT Publishers in Uphold

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#479] opened 2018-01-12 00:06 UTC
Owners might revoke permissions of the BAT Publishers app within Uphold to access Uphold datas. In this case we can't do settlements.

When we detect this we need to send an email to owners to confirm:

- The deauth was a mistake -- please reauth so we can give you the BATs

- You really want to deauthorize us and do not wish to get the BATs. that's okay -- no action required. Also we only want to send this message once and avoid bothering them.

See also:
#462
https://github.com/brave-intl/publishers/issues/468#issuecomment-356967706

**Comment by nvonpentz** [comment] 2018-03-14 16:02
Related to #133

**Comment by nvonpentz** [comment] 2018-04-11 16:57
Duplicate of #462

**Closed by nvonpentz** 2018-04-11 16:57 UTC
Labels: 3 P3
