### ISSUE TITLE
Wordpress verification broken

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#546] opened 2018-01-26 03:04 UTC
Many users have reported that they are unable to verify their wordpress sites after the updated plugin was released.  Please read https://community.brave.com/t/trouble-with-site-verification/12958.

Most users are waiting to get their 'verification complete' emails, though it never comes.

This could be an issue with Eyeshade. cc @mrose17

**Comment by nvonpentz** [comment] 2018-02-21 15:08
I've heard very few problems about this recently.  This could potentially be resolved.

**Comment by mrose17** [comment] 2018-02-21 16:41
@alexwykoff  - what's your thinking on this?

**Comment by nvonpentz** [comment] 2018-02-21 17:20
Also these publishers are effected: https://github.com/brave-intl/internal/issues/20

I have confirmed at least one case in which the plugin does not update .well-known https://bravesoftware.slack.com/archives/C0KHGGEUW/p1519228312000608

**Comment by nvonpentz** [comment] 2018-03-23 13:33
Short term solution implemented in #743

**Comment by corymcdonald** [comment] 2019-09-16 18:43
Closing this - I believe the issue is with conflicting Wordpress plugins that redirect all traffic using the same HTTP redirect rules that we use, however we've yet to find someone that can give us a list of plugins this might be interfering with.

DNS Verification seems to work with these publishers who can't seem to get the wordpress plugin working.

**Closed by corymcdonald** 2019-09-16 18:43 UTC
Labels: Bug 🐛, P3, research
